### PR TITLE
callback PlaybackStatusCompat.STATE_ERROR when media not found

### LINKED ISSUE #64: NullPointerException occurs when trying to play deleted music
### Procedure
1. Launch stamp app and load music contents
2. Delete a music content with another application
3. Launch stamp app again and play deleted music -> Exception

### Root of cause
In [LocalPlayback.play(QueueItem item) line 182](https://github.com/sjnyag/stamp/blob/master/app/src/main/java/com/sjn/stamp/media/playback/LocalPlayback.java#L182)

```java
item.getDescription().getMediaUri()
```
Return value of above statement can be null if media does not exist. And calling method for null instance caused Exception.

### Suggestion
In [PlaybackManager.handlePlayRequest()](https://github.com/sjnyag/stamp/blob/master/app/src/main/java/com/sjn/stamp/media/playback/PlaybackManager.java#L92),

```java
MediaSessionCompat.QueueItem currentMusic = mQueueManager.getCurrentMusic();
if (currentMusic != null) {
  ...
  mPlayback.play(currentMusic);
}
```

the system is checking if currentMusic is null.
If QueueManager.getCurrentMusic() returns null, this problem does not occur.
```java
public MediaSessionCompat.QueueItem getCurrentMusic() {
    if (!QueueHelper.isIndexPlayable(mCurrentIndex, getPlayingQueue())) {
        return null;
    }
    return getPlayingQueue().get(mCurrentIndex);
}
```

I think QueueHelper.isIndexPlayable() should return **false** if actual music is deleted.
```java
public static boolean isIndexPlayable(int index, List<MediaSessionCompat.QueueItem> queue) {
    return (queue != null && index >= 0 && index < queue.size());
}
```
Also, you have to increment mCurrentIndex and try to play next music like following.

```java
if (currentMusic != null) {
  ...
  mPlayback.play(currentMusic);
} else {
  int nextIndex = mQueueManager.getCurrentIndex() + 1;
  mQueueManager.setCurrentQueueIndex(nextIndex);
  // or mQueueManager.skipQueuePosition(1);
  mPlayback.play(currentMusic);
  
  // Please note next music can also be null
  // Also, if you skip music by while statement, consider all music is deleted situation that never to be playable
}
```

### Exception log
```
08-03 15:05:30.160 32551 32551 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
08-03 15:05:30.160 32551 32551 E AndroidRuntime:        at com.sjn.stamp.media.playback.LocalPlayback.play(LocalPlayback.java:182)
08-03 15:05:30.160 32551 32551 E AndroidRuntime:        at com.sjn.stamp.media.playback.PlaybackManager.handlePlayRequest(PlaybackManager.java:101)
08-03 15:05:30.160 32551 32551 E AndroidRuntime:        at com.sjn.stamp.media.playback.PlaybackManager$MediaSessionCallback.onPlayFromMediaId(PlaybackManager.java:402)
08-03 15:05:30.160 32551 32551 E AndroidRuntime:        at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onPlayFromMediaId(MediaSessionCompat.java:1066)
08-03 15:05:30.160 32551 32551 E AndroidRuntime:        at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onPlayFromMediaId(MediaSessionCompatApi21.java:180)
08-03 15:05:30.160 32551 32551 E AndroidRuntime:        at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1471)
08-03 15:05:30.160 32551 32551 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
08-03 15:05:30.160 32551 32551 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:241)
08-03 15:05:30.160 32551 32551 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6223)
08-03 15:05:30.160 32551 32551 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-03 15:05:30.160 32551 32551 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
08-03 15:05:30.160 32551 32551 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

### PR DESCRIPTION
**Pull request by sjnyag**
FIX #64 

> Also, you have to increment mCurrentIndex and try to play next music like following.

`PlaybackManager.handlePlayRequest()` is called not only "when a music is completed and try to play next" but also "when user touches a song on ListView".
It's a little confusing if wrong song played when user touches a song on ListView.

And it's much to do above process only "when a music is completed and try to play next".

### CODE REVIEW

**Comment by subaru44k** [comment]
> It's a little confusing if wrong song played when user touches a song on ListView.

I agree your comment.

But, what will happen if a user selects playlist whose first music content is deleted?
I guess the user expectation is 
- Skip first(deleted) content
- Playback next content

Do your modification also work for above case?

**Comment by sjnyag** [comment]
I agree you but low priority!

**Comment by subaru44k** [comment]
I understand.
Thanks for the consideration.

**Comment by sjnyag** [comment]
Create new issue #68

**Pull request merged**
